version: '3'
services:
  db:
    container_name: todo_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_db_test
    ports:
      - 6000:5432
