version: '3'
services:
  api:
    build: .
    environment:
      - DB_HOST=todo_postgres
      - DB_PORT=5432
    ports:
      - 3000:3000
  db:
    container_name: todo_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo-db
    ports:
      - 6000:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
