version: '3'
services:
  api:
    build: .
    env_file:
      - db.env
    ports:
      - '3000:3000'
  db:
    container_name: todo_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER_DOCKER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DOCKER}
      POSTGRES_DB: ${DB_NAME_DOCKER}
    ports:
      - ${DB_PORT_DOCKER}
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL_DOCKER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD_DOCKER}
    ports:
      - '5050:80'
